# Generated by Django 5.2.16 on 2026-07-07 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeighingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor_polisi', models.CharField(max_length=20)),
                ('nama_driver', models.CharField(max_length=100)),
                ('jenis_muatan', models.CharField(blank=True, max_length=100)),
                ('jenis_timbang', models.CharField(choices=[('gross', 'Timbangan Masuk (Gross)'), ('tare', 'Timbangan Keluar (Tare)')], max_length=10)),
                ('berat_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('berat_bersih_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('created_at_local', models.DateTimeField()),
                ('created_at_server', models.DateTimeField(auto_now_add=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced')], default='synced', max_length=10)),
                ('pasangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='weighing.weighingtransaction')),
            ],
            options={
                'ordering': ['-created_at_server'],
                'indexes': [models.Index(fields=['nomor_polisi'], name='weighing_we_nomor_p_a4e592_idx'), models.Index(fields=['created_at_local'], name='weighing_we_created_ceea77_idx')],
            },
        ),
    ]
