# Generated by Django 5.2.16 on 2026-08-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0003_cargo_destination_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('both', 'Customer & Supplier')], default='customer', max_length=10)),
                ('contact', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='WeighingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('deduction_percent', models.DecimalField(decimal_places=2, default=0, help_text='Potongan berat otomatis dalam persen (0 = tidak ada potongan)', max_digits=5)),
                ('require_driver', models.BooleanField(default=True, help_text='Nama driver wajib diisi')),
                ('require_destination', models.BooleanField(default=True, help_text='Tujuan wajib diisi')),
                ('require_cargo', models.BooleanField(default=True, help_text='Jenis muatan wajib diisi')),
                ('require_customer', models.BooleanField(default=False, help_text='Customer/Supplier wajib diisi')),
                ('require_unit', models.BooleanField(default=False, help_text='Jenis unit kendaraan wajib diisi')),
                ('max_weight_kg', models.DecimalField(decimal_places=2, default=0, help_text='Batas berat kendaraan maksimal dalam kg (0 = tidak dibatasi)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
