# Generated by Django 5.2.16 on 2026-08-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0004_customersupplier_unit_weighingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingtransaction',
            name='berat_potongan_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='customer_supplier',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='deduction_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='weighing_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
