# Generated by Django 5.2.16 on 2026-08-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0005_weighingtransaction_berat_potongan_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeighingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('indicator_type', models.CharField(choices=[('CAS', 'CAS (Format Detail)'), ('GSC', 'GSC (Format Sederhana)')], default='CAS', max_length=10)),
                ('baud_rate', models.IntegerField(default=9600)),
                ('data_bits', models.IntegerField(default=8)),
                ('stop_bits', models.IntegerField(default=1)),
                ('parity', models.CharField(default='none', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
