# Generated by Django 5.2.16 on 2026-10-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0006_weighingscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingtransaction',
            name='customer_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='harga_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='total_harga',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
