# Generated by Django 5.2.16 on 2026-10-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0007_weighingtransaction_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='JEMBATAN TIMBANG', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('npwp', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Profil Perusahaan',
                'verbose_name_plural': 'Profil Perusahaan',
            },
        ),
    ]
