# Generated by Django 5.2.16 on 2026-10-01 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0008_siteprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingtransaction',
            name='site_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='weighing.siteprofile'),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='site_profile_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='site_profile_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='site_profile_npwp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='site_profile_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
