# Generated by Django 5.2.16 on 2026-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0009_add_site_profile_to_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_name', models.CharField(help_text='Nama jenis muatan (harus sesuai dengan yang diinput di form timbang)', max_length=100, verbose_name='Jenis Muatan')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Harga per kg (Rp)')),
                ('effective_date', models.DateField(help_text='Harga berlaku mulai tanggal ini', verbose_name='Berlaku Mulai')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Master Harga',
                'verbose_name_plural': 'Master Harga',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
